### ISSUE TITLE
[新功能]: 定时备份｜自动清理｜玩家提醒

### ISSUE THREAD

**Issue by TRDSCSH** [MengHanLOVE1027/EasyBackuper#1]
> 我在 [MineBBS](https://www.minebbs.com/resources/easybackuper-eb.7771/) 上面看到了这个插件，我认为这个插件做得很好，让我不需要再关服备份存档。
> 同时我有一些想法自认为可以让这个插件变得更好，所以前来提出 issue，希望作者可以考虑实现下面的这些功能。🙏

我建议添加以下功能:
- [x] 定时备份: 使用 [Cron 表达式](https://en.wikipedia.org/wiki/Cron)设定定时任务
- [x] 自动清理较早的备份: 设置一个最大备份数量，如果备份文件的数量超出，则删除较早的备份
- [x] 备份时通知玩家: 在游戏中提示在线玩家 `服务器存档开始备份` `备份结束` 之类的

感谢考虑 ☕️

**Comment by MengHanLOVE1027** [comment]
感谢您提出的建议，我会对照此清单进行功能上的添加，将会在近期完成此清单

**Comment by MengHanLOVE1027** [comment]
于 2024/4/20 15:32 完成 “备份时通知玩家: 在游戏中提示在线玩家 `服务器存档开始备份` `备份结束` 之类的” 清单

**Comment by MengHanLOVE1027** [comment]
于 2024/4/20 21:53 完成 “自动清理较早的备份: 设置一个最大备份数量，如果备份文件的数量超出，则删除较早的备份” 清单

**Comment by MengHanLOVE1027** [comment]
于 2024/4/21 16:20 完成 “定时备份: 使用 [Cron 表达式](https://en.wikipedia.org/wiki/Cron)设定定时任务” 清单

**Comment by MengHanLOVE1027** [comment]
稍后进行版本发布

**Comment by TRDSCSH** [comment]
> 于 2024/4/20 21:53 完成 “自动清理较早的备份: 设置一个最大备份数量，如果备份文件的数量超出，则删除较早的备份” 清单

感谢大佬的辛苦付出！
我体验了一下这个插件，发现了一个问题：这个插件只在**服务端启动时**清理备份。
而我觉得，在**存档备份成功后**也需要清理一遍之前的备份文件。

**Comment by MengHanLOVE1027** [comment]
> > 于 2024/4/20 21:53 完成 “自动清理较早的备份: 设置一个最大备份数量，如果备份文件的数量超出，则删除较早的备份” 清单
> 
> 感谢大佬的辛苦付出！ 我体验了一下这个插件，发现了一个问题：这个插件只在**服务端启动时**清理备份。 而我觉得，在**存档备份成功后**也需要清理一遍之前的备份文件。

介于本 Issue 已完成，我将会关闭此议题，若有任何疑问可以重提新的 问题Issue 或在 [[新改进]: 在 服务器启动时 清理 or 在此基础上每当备份时也要 清理 #2](https://github.com/MengHanLOVE1027/EasyBackuper/issues/2) 中继续提出意见，感谢您对本插件的支持和鼓励🎉
