### ISSUE TITLE
[新改进]: 在 服务器启动时 清理 or 在此基础上每当备份时也要 清理

### ISSUE THREAD

**Issue by MengHanLOVE1027** [MengHanLOVE1027/EasyBackuper#2]
> > 于 2024/4/20 21:53 完成 “自动清理较早的备份: 设置一个最大备份数量，如果备份文件的数量超出，则删除较早的备份” 清单
>
> 感谢大佬的辛苦付出！
> 我体验了一下这个插件，发现了一个问题：这个插件只在**服务端启动时**清理备份。
> 而我觉得，在**存档备份成功后**也需要清理一遍之前的备份文件。
> _Originally posted by @TRDSCSH in https://github.com/MengHanLOVE1027/EasyBackuper/issues/1#issuecomment-2068510367_

改进功能：

- [x] 对 **备份** 模块进行优化
- [x] 在 **存档备份成功后** 也需要清理一遍之前的备份文件，另外提供选择自主权（只在 **服务端启动时** 清理备份 or 在 **存档备份成功后** 清理一遍之前的备份文件）

**Comment by MengHanLOVE1027** [comment]
我将会在近期的节假日内完成此项 issue，因为幺七钟烤事力QAQ @TRDSCSH

**Comment by TRDSCSH** [comment]
> 我将会在近期的节假日内完成此项 issue，因为幺七钟烤事力QAQ @TRDSCSH

没事，大佬慢慢来。~~我可以临时在备份函数末尾调用清理函数（~~
祝考试顺利！

**Comment by MengHanLOVE1027** [comment]
话说怎么联系你捏( @TRDSCSH

**Comment by TRDSCSH** [comment]
> 话说怎么联系你捏( @TRDSCSH

发送 QQ 好友申请了捏（ @MengHanLOVE1027

**Comment by MengHanLOVE1027** [comment]
由于最近被班主任硬控，随缘进行更新，抱歉了😇

**Comment by TRDSCSH** [comment]
> 由于最近被班主任硬控，随缘进行更新，抱歉了😇

没事，不急着更新，学业为重

**Comment by MengHanLOVE1027** [comment]
于 2024/6/1 11:18 完成 “在 存档备份成功后 也需要清理一遍之前的备份文件，另外提供选择自主权（只在 服务端启动时 清理备份 or 在 存档备份成功后 清理一遍之前的备份文件）” 清单

**Comment by MengHanLOVE1027** [comment]
于 2024/6/1 11:39 完成 “对 备份 模块进行优化” 清单

**Comment by MengHanLOVE1027** [comment]
介于本issue已完成，现已关闭，如有疑问可以继续提issue
