### ISSUE TITLE
[适配请求] 适配LeviLamina 0.13.x

### ISSUE THREAD

**Issue by CJYKK** [MengHanLOVE1027/EasyBackuper#4]
如题。目前在使用 LeviLamina v0.13.3 的服务器上用lip安装时会报错
```
[ERRO] 
    Missing prerequisites:
    github.com/LiteLDev/LeviLamina: 0.12.x
```

**Comment by MengHanLOVE1027** [comment]
已删除tooth.json文件中对Levimina的版本依赖，现在应该可以成功下载安装了
并且以后再也不设置对Levimina的版本依赖，除非特殊需要
[Update tooth.json(取消对Levimina的版本限定)](https://github.com/MengHanLOVE1027/EasyBackuper/commit/28dd4f34cf26d570a6fe62e436c2a65bbbf8adc7)

**Comment by MengHanLOVE1027** [comment]
如果没有啥问题的话我就关闭了
